---
apiVersion: batch/v1
kind: Job
metadata:
  name: rglenn1-mist-tf-gpu-#COUNT#
  namespace: yn-gpu-workload
  labels:
      k8s-user: rglenn1
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        "nvidia.com/gpu.present": "true"
      securityContext:
        runAsUser: 276957
        runAsGroup: 600651
        fsGroup: 600651
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/rglenn1/mist-tf
          command: ["/bin/bash","-c"]
          args: ['python main.py  --data /rsrch1/ip/rglenn1/data/nihil_data/nihil_data_T1/dataset.json  --results /rsrch1/ip/rglenn1/data/nihil_data/Model_#COUNT# --model nnunet --pocket --xla --amp --patch-size 256 128 128  --epochs 1000   --kfold False --train_val_test_csv /rsrch1/ip/rglenn1/data/nihil_data/nihil_data_T1/t1_allexperiments_datasplit12_23_2023_kube.csv  --split_column "Model #COUNT#" ']
          workingDir: "/rsrch1/ip/rglenn1/segLiverWkspce/docker_mist/pytoch_MIST/mist-tf_#COUNT#"
          env:
          - name: HOME
            value: "/rsrch1/ip/rglenn1"
          - name: MORFEUS
            value: "/Morfeus/Nihil/SMIT/fine_tuning_data"  
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: home
              mountPath: "/rsrch1/ip/rglenn1"
            - name: home
              subPath: "segLiverWkspce/docker_mist/pytoch_MIST/mist-tf_#COUNT#"
              mountPath: "/rsrch1/ip/rglenn1/segLiverWkspce/docker_mist/pytoch_MIST/mist-tf_#COUNT#"
            - name: morfeus
              mountPath: "/Morfeus/Nihil/SMIT/fine_tuning_data"



          resources:
            limits:
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21474836480'
        - name: home
          persistentVolumeClaim:
            claimName: rglenn1-gpu-home
        - name: morfeus
          hostPath:
            path: "/Morfeus/Nihil/SMIT/fine_tuning_data"
            type: Directory

          
      restartPolicy: Never

